### PR TITLE
Angelica chowdhury

### PR DESCRIPTION
**Pull request by angie-acho0697**
This is including all the team members' names

### CODE REVIEW

**Comment by louisrankin** [comment]
Thanks for the addition

**Review by louisrankin — CHANGES_REQUESTED** [review]
My name is spelled "Rankin"

**Comment by angie-acho0697** [comment]
Corrected, autocorrect changes it to Ranking sorry

**Comment by angie-acho0697** [comment]
Corrected, autocorrect changed it to Ranking sorry

**Review by louisrankin — APPROVED** [review]
Thanks for fixing that up

**Pull request merged**
