### PR TITLE
Scene graph as input to test in VM 

### PR DESCRIPTION
**Pull request by angie-acho0697**
@zachphillipps  can you please approve my pull request thanks

### CODE REVIEW

**Comment by zachphillipps** [comment]
With scene graph code updated, propose merging of branches.

**Review by zachphillipps — COMMENTED** [review]
Propose merging of latest version of scene-graph-as-input branch

**Review by zachphillipps — COMMENTED** [review]
Apply pull request on latest version only.

**Review by louisrankin — APPROVED** [review]
This is a tough one to review as it includes the Demo.py file which comes from another branch. We should be able to merge this and then merge the other branch on top of it.

There are also multiple revisions for the notebooks. We should try and avoid doing this as it makes the git project unnecessarily complicated.

**Pull request merged**
